### PR TITLE
bumps the nio4r gem version dependency

### PR DESCRIPTION
**Pull request by kylekeesling**
so it can work with newer versions of rails

### CODE REVIEW

**Comment by kylekeesling** [comment]
I was having trouble installing this on Rails 5.1.4 and bundler indicated it was because `ActionCable` requires ~>2

Here's the trace for reference:

`Bundler could not find compatible versions for gem "nio4r":
  In snapshot (Gemfile.lock):
    nio4r (= 2.1.0)

  In Gemfile:
    trix was resolved to 0.11.0, which depends on
      rails (< 5.2, > 4.1) was resolved to 5.1.4, which depends on
        actioncable (= 5.1.4) was resolved to 5.1.4, which depends on
          nio4r (~> 2.0)

    gpgmeh was resolved to 0.1.4, which depends on
      nio4r (~> 1.2.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

**Comment by nerdrew** [comment]
I'll look at the test failures today. I haven't looked at the changelog for nio4r yet, but I'll look at that too.

**Comment by kylekeesling** [comment]
Ok great. I attempted to run the test suite myself but it just ended up in a loop that was continually trying to add keys to my GPG keychain and I had to restart my machine :)

As far as the changelog goes, here's what I [grabbed from the repo](https://github.com/socketry/nio4r/blob/master/CHANGES.md):

**2.1.0 (2017-05-28)**
#130 Add -fno-strict-aliasing flag when compiling C ext. (@junaruga)
#146 Use non-blocking select when a timeout of 0 is given. (@tarcieri)
#147 Update to libev 4.24. (@tarcieri)
#148 Switch to the libev 4 API internally. (@tarcieri)

**2.0.0 (2016-12-28)**
#53 Limit lock scope to prevent recursive locking. (@johnnyt)
#95 NIO::ByteBuffer Google Summer of Code project. (@UpeksheJay, @tarcieri)
#111 NIO::Selector#backend introspection support. (@tarcieri)
#112 Upgrade to libev 4.23. (@tarcieri)
#119 Disambiguate wakeup vs timeout (fixes #63, #66). (@tarcieri)
#124 Monitor interests API improvements. (@tarcieri)
Drop Ruby 2.0 and 2.1 support, require Ruby 2.2.2+. (@tarcieri)

**1.2.1 (2016-01-31)**
Fix bug in the JRuby backend which cases indefinite blocking when small timeout values are passed to the selector

**Comment by tarcieri** [comment]
There aren't particularly major changes. It looks like all of the test failures are unrelated.

**Comment by nerdrew** [comment]
Dammit. If you update rubocop to 0.50.0 it enables [Performance/UnfreezeString](https://github.com/bbatsov/rubocop/issues/4968) which looks like it isn't compatible ruby 2.2 syntax :(

Thoughts on maintaining ruby 2.2 compatibility?

**Comment by nerdrew** [comment]
Also, I added a bunch of commits here: https://github.com/square/gpgmeh/pull/5

@tarcieri @kylekeesling

**Comment by nerdrew** [comment]
Merged as https://github.com/square/gpgmeh/pull/5

**Pull request merged**
