### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nerdrew**

### CODE REVIEW

**Comment by nerdrew** [comment]
@tarcieri @kylekeesling Want to review?

@kylekeesling Do you mind if I include your commit in this PR? If you mind, I can drop your commit here, merge this PR, and after you can rebase your PR. Otherwise, I can just merge this PR with your commit.

**Comment by kylekeesling** [comment]
Nope go right ahead!  Need me to close out my PR then?

**Comment by nerdrew** [comment]
@kylekeesling looks like github is pretty clever. It closed your PR as merged. :)

**Comment by nerdrew** [comment]
@kylekeesling released as 0.1.5.

**Comment by kylekeesling** [comment]
Awesome! I'll get in and switch my Gemfile to use this version rather than my fork. Thanks for the help!

**Pull request merged**
